### ISSUE TITLE
Renaming climate devices

### ISSUE THREAD

**Issue by Dinth** [cgarwood/homeassistant-zwave_mqtt#124]
- Home Assistant version: 0.109.1
- ozwdaemon version or add-on version: 1.0.15
- homeassistant-zwave_mqtt version: 0.0.14

I have just noticed that automatic renaming of entity ids doesnt work for climate components.
How to reproduce: 
1. Add a thermostat to OZWdaemon.
2. Open Integraitions -> Zwave-over-MQTT
3. Click on the newly added thermostat.
4. Click on the cog icon, enter a new name and room.
5. "Do you want to rename entity ids of your entities" popup shows up. Click Yes.
6. Entity names are renamed, but entity ids are not. 

I havent seen such behavior with any other type of devices.

**Comment by joshtbernstein** [comment]
Strangely this worked for _my_ climate device (all three instances), but it didn't work for my doorbell sensor.

**Comment by Dinth** [comment]
But still its not totally random, it worked fro all my devices except all five thermostats.

**Comment by cgarwood** [comment]
I know all of the entity ID's have to have some bit of matching text for it to rename them (not sure how much or what it requires), but I've seen renaming randomly fail on devices from other integrations/components too.

**Comment by marcelveldt** [comment]
I just published version .15 to HACS, please have a test with that.
As we're already implementing the code into core Hass it would be great to get some feedback if this issue is resolved.

WARNING: version .15 contained a change to the internal id matching so it is normal that you need to rename your entities/devices again.

**Comment by kpine** [comment]
When renaming with .15, I still get the error message `not a valid value for dictionary value @ data['disabled_by']. Got 'integration'`. The enabled entities are renamed correctly, but the disabled ones are not. Are both of those expected behavior?

I have a second Device instance of the thermostat (mult-channel) and the Device rename works the same, enabled child entities are renamed, disabled are not, and the error message is printed. However, a difference here is that the entity friendly names are not updated.

Instance 2, renamed to "Home Unused", only entity name is updated:
![image](https://user-images.githubusercontent.com/791794/81320308-d2ae4180-9045-11ea-9a1c-1deec7eefcdf.png)

Meanwhile, with Instance 1 both friendly name and entity names are changed:
![image](https://user-images.githubusercontent.com/791794/81320376-f2456a00-9045-11ea-8173-e66322f8b4c7.png)

**Comment by Dinth** [comment]
> When renaming with .15, I still get the error message `not a valid value for dictionary value @ data['disabled_by']. Got 'integration'`. The enabled entities are renamed correctly, but the disabled ones are not. Are both of those expected behavior?

There's already an open issue for that: https://github.com/cgarwood/homeassistant-zwave_mqtt/issues/111

**Comment by kpine** [comment]
Correct, thanks. I couldn't remember where that was. Given that, the only issue I still observed then was the friendly names not being changed on the second device instance.

**Comment by marcelveldt** [comment]
Renaming devices is not perfect in Home Assistant and it's not an issue related to this component. 
I'll close this issue here as we're already integrating into core.
