### ISSUE TITLE
Mark entities unavailable if ozwdaemon goes offline

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/homeassistant-zwave_mqtt#25]
If an ozwdaemon instance goes offline we should mark the entities belonging to that instance as unavailable

**Comment by MartinHjelmare** [comment]
Here are the qt openzwave docs for client status that we will need to use:
https://github.com/OpenZWave/qt-openzwave/blob/master/docs/MQTT.md#mqtt-client-status

Here's the status property in openzwavemqtt:
https://github.com/cgarwood/python-openzwave-mqtt/blob/994ff9eaf481f868f678669d478a1b3b54517377/openzwavemqtt/models/instance_status.py#L11-L14

**Comment by balloob** [comment]
It's already published as will message, so we should be able to rely on this always being set to offline.

**Comment by MartinHjelmare** [comment]
Yes.

**Comment by marcelveldt** [comment]
It's a bit more difficult because when OZW restarts, all nodes (+ it's values) are removed and re-added. Looking at the will message will only solve the usecase where the OZW and/or MQTT server are (temporary) unavailable, not the situation where OZW is restarted/restarting. 

I've created a fix for the latter, will submit the PR later today, along with some more small fixes for several outstanding issues.

**Comment by Fishwaldo** [comment]
You could only act on topics/messages when OZW status is equal to "started". Anything else, OZW would be in a indeterminate state. (maybe populating topics etc).

**Comment by marcelveldt** [comment]
Yeah, I figured. Fix in new PR coming up. Thanks!

**Comment by marcelveldt** [comment]
Closed by #93 which will mark entities unavailable when OZW is not in a valid state (e.g. restarting). This can be even improved by watching the LWT message of the OZW daemon on MQTT so we can also track the MQTT connection or OZW broker to be completely offline (non clean shutdown). A normal/clean shutdown of OZW is catched by the status.

EDIT: This is actually the LWT message so things will work automagically ;-)
